version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      # ローカルマシン側が Linux な場合、ファイルシステムに違いはないのでファイルを変換する手間がないためファイルの共有設定をしていてもパフォーマンスの低下は起きないそうです。なのでこの設定はしなくてOK
      # - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nn_chat
      TZ: 'Asia/Tokyo'
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data
